[book]
title = "Omikuji"
description = "A universal, native game launcher for Linux."
authors = ["reakjra"]
language = "en"
src = "src"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["custom.css"]
git-repository-url = "https://github.com/omikuji-launcher/omikuji"
edit-url-template = "https://github.com/omikuji-launcher/omikuji/edit/master/docs/site/src/{path}"

[output.html.fold]
enable = true
level = 1
