// apply_* prefix becuase cxx-qt already generates setXxx for qproperties;
// using the same name would collide. each apply_* sets the property then atonmically persists
// the bridge module + all qproperty plumbing is generated by kushi (see build.rs); this file
// keeps only the parts with actual decisions: persist window, custom applies, json accessors, watcher

use cxx_qt::Threading;
use omikuji_core::fs_watcher::FileWatcher;
use omikuji_core::app_settings::{CategoryEntry, KvSet, LogRule, AppSettings, app_settings_path};
use std::collections::BTreeMap;
use std::time::{Duration, Instant};

unsafe extern "C" {
    fn omikuji_set_app_font(family: *const std::os::raw::c_char);
    fn omikuji_available_languages_json() -> *const std::os::raw::c_char;
}

include!(concat!(env!("OUT_DIR"), "/app_settings_bridge.rs"));

include!(concat!(env!("OUT_DIR"), "/icon_names.rs"));

impl qobject::AppSettingsBridge {
    fn persist(mut self: Pin<&mut Self>) {
        // 600ms covers the 150ms debounce plus qt_thread hop slack
        self.as_mut().rust_mut().get_mut().suppress_reload_until =
            Some(Instant::now() + Duration::from_millis(600));
        if let Err(e) = self.snapshot().save() {
            tracing::error!("save failed: {}", e);
        }
    }

    fn apply_ui_scale(mut self: Pin<&mut Self>, value: f64) {
        let clamped = value.clamp(0.7, 2.0);
        self.as_mut().set_ui_scale(clamped);
        self.persist();
    }

    fn apply_card_flow(mut self: Pin<&mut Self>, value: &cxx_qt_lib::QString) {
        let v = value.to_string();
        let allowed = matches!(v.as_str(), "left" | "center" | "right");
        let final_v = if allowed {
            value.clone()
        } else {
            cxx_qt_lib::QString::from("center")
        };
        self.as_mut().set_card_flow(final_v);
        self.persist();
    }

    fn apply_card_sort(mut self: Pin<&mut Self>, value: &cxx_qt_lib::QString) {
        let v = value.to_string();
        let allowed = matches!(v.as_str(), "default" | "a-z" | "z-a" | "custom");
        let final_v = if allowed {
            value.clone()
        } else {
            cxx_qt_lib::QString::from("default")
        };
        self.as_mut().set_card_sort(final_v);
        self.persist();
    }

    fn apply_follow_system_colors(mut self: Pin<&mut Self>, value: bool) {
        self.as_mut().set_follow_system_colors(value);
        self.as_mut().persist();
        self.as_mut().theme_changed();
    }

    fn apply_follow_system_font(mut self: Pin<&mut Self>, value: bool) {
        self.as_mut().set_follow_system_font(value);
        self.as_mut().persist();
        self.as_mut().apply_effective_font();
        self.as_mut().theme_changed();
    }

    fn apply_font_family(mut self: Pin<&mut Self>, value: &cxx_qt_lib::QString) {
        self.as_mut().set_font_family(value.clone());
        self.as_mut().persist();
        self.as_mut().apply_effective_font();
        self.as_mut().theme_changed();
    }

    fn reload_extras(mut self: Pin<&mut Self>, _s: &AppSettings) {
        self.as_mut().theme_changed();
    }

    fn available_icons_json(&self) -> cxx_qt_lib::QString {
        let json = serde_json::to_string(ICON_NAMES).unwrap_or_else(|_| "[]".to_string());
        cxx_qt_lib::QString::from(&json)
    }

    fn apply_effective_font(self: Pin<&mut Self>) {
        let family = if self.follow_system_font {
            String::new()
        } else {
            self.font_family.to_string()
        };
        if let Ok(c) = std::ffi::CString::new(family) {
            unsafe { omikuji_set_app_font(c.as_ptr()) }
        }
    }

    fn color_override(&self, token: &cxx_qt_lib::QString) -> cxx_qt_lib::QString {
        let key = token.to_string();
        let val = self.color_overrides.get(&key).cloned().unwrap_or_default();
        cxx_qt_lib::QString::from(&val)
    }

    fn set_color_override(
        mut self: Pin<&mut Self>,
        token: &cxx_qt_lib::QString,
        hex: &cxx_qt_lib::QString,
    ) {
        let key = token.to_string();
        let val = hex.to_string();
        let map = &mut self.as_mut().rust_mut().get_mut().color_overrides;
        if val.is_empty() {
            map.remove(&key);
        } else {
            map.insert(key, val);
        }
        self.as_mut().persist();
        self.as_mut().theme_changed();
    }

    fn overrides_json(&self) -> cxx_qt_lib::QString {
        let json =
            serde_json::to_string(&self.color_overrides).unwrap_or_else(|_| "{}".to_string());
        cxx_qt_lib::QString::from(&json)
    }

    fn available_fonts_json(&self) -> cxx_qt_lib::QString {
        let json = serde_json::to_string(&list_system_fonts()).unwrap_or_else(|_| "[]".to_string());
        cxx_qt_lib::QString::from(&json)
    }

    fn available_languages_json(&self) -> cxx_qt_lib::QString {
        let ptr = unsafe { omikuji_available_languages_json() };
        if ptr.is_null() {
            return cxx_qt_lib::QString::from("[]");
        }
        let json = unsafe { std::ffi::CStr::from_ptr(ptr) }
            .to_string_lossy()
            .into_owned();
        cxx_qt_lib::QString::from(&json)
    }

    fn init_watcher(mut self: Pin<&mut Self>) {
        if self.as_ref().rust().watcher.is_some() {
            return;
        }
        let path = app_settings_path();
        let qt_thread = self.as_mut().qt_thread();
        let watcher = FileWatcher::watch(path, move || {
            let _ = qt_thread.queue(move |mut obj: Pin<&mut qobject::AppSettingsBridge>| {
                let within_window = obj
                    .as_ref()
                    .rust()
                    .suppress_reload_until
                    .map(|until| Instant::now() < until)
                    .unwrap_or(false);
                if within_window {
                    return;
                }
                obj.as_mut().reload_from_disk();
            });
        });
        match watcher {
            Ok(w) => {
                self.as_mut().rust_mut().get_mut().watcher = Some(w);
                tracing::debug!("watching {} via notify", app_settings_path().display());
            }
            Err(e) => tracing::error!("failed to start watcher: {e}"),
        }
    }
}

fn list_system_fonts() -> Vec<String> {
    let output = std::process::Command::new("fc-list")
        .args([":scalable=true:fontformat=TrueType", "family"])
        .output();
    let Ok(out) = output else {
        return Vec::new();
    };
    if !out.status.success() {
        return Vec::new();
    }
    let mut set = std::collections::BTreeSet::new();
    for line in String::from_utf8_lossy(&out.stdout).lines() {
        if let Some(name) = line.split(',').next() {
            let trimmed = name.trim();
            if !trimmed.is_empty() {
                set.insert(trimmed.to_string());
            }
        }
    }
    set.into_iter().collect()
}
