name: Build (Arch)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring
          pacman -Syu --noconfirm pkg-config \
          base-devel \
          sudo \
          cmake \
          systemd-libs \
          fuse2 \
          wget \
          protobuf \
          rust \
          cmake \
          libxkbcommon \
          xcb-util-cursor \
          libcups \
          glib2 \
          libproxy \
          qt6-base \
          qt6-tools \
          qt6-wayland \
          qt6-shadertools \
          libfbclient \
          mariadb \
          unixodbc \
          postgresql-libs \
          jxrlib

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Build
        run: |
          sudo -u builder sh <<'EOF'
          set -e
          cargo build --release -p omikuji
          chmod +x ./packaging/make-appimage.sh
          ./packaging/make-appimage.sh
          EOF

      - name: Upload artifact/s
        uses: actions/upload-artifact@v7
        with:
          name: omikuji-appimage
          path: Omikuji-x86_64.AppImage
          archive: false
