name: Build Flatpak

on:
  workflow_dispatch:

jobs:
  flatpak:
    name: Build Flatpak
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Flatpak dependencies
        run: |
          sudo apt update
          sudo apt install -y flatpak flatpak-builder git

          flatpak --user remote-add --if-not-exists flathub \
            https://dl.flathub.org/repo/flathub.flatpakrepo

          # Install KDE runtime + Wine base + Rust
          flatpak --user install -y flathub \
            org.kde.Sdk//6.10 \
            org.kde.Platform//6.10 \
            org.winehq.Wine//stable-25.08 \
            org.freedesktop.Sdk.Extension.rust-stable//25.08

      - name: Build Flatpak
        run: |
          cd flatpak
          mkdir -p build-dir
          flatpak-builder --user \
            --force-clean \
            --repo=repo \
            build-dir \
            io.github.reakjra.omikuji.yaml

      - name: Export Flatpak bundle
        run: |
          flatpak build-bundle repo \
            omikuji.flatpak \
            io.github.reakjra.omikuji

      - name: Upload Flatpak artifact
        uses: actions/upload-artifact@v6
        with:
          name: omikuji-flatpak
          path: omikuji.flatpak
